version: '3.1'
services:
  mongo-db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=MyPa$$w0rd
    ports:
      - "27017:27017"
    command: mongod
